# Generated by Django 5.2.12 on 2026-03-10 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source_type', models.CharField(default='txt', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='world',
            name='factions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='world',
            name='locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='world',
            name='main_conflict',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='world',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds', to='game.book'),
        ),
    ]
