# Generated by Django 5.2.12 on 2026-03-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_book_world_factions_world_locations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('strategy', models.CharField(choices=[('fixed', 'Fixed Price'), ('negotiation', 'Negotiation'), ('barter', 'Barter')], max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to='game.character')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_orders', to='game.storysession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('avg_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='game.character')),
            ],
            options={
                'unique_together': {('character', 'item_name')},
            },
        ),
    ]
