# Generated by Django 5.2.12 on 2026-03-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_tradeorder_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorder',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='side',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=10),
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic')], default='common', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_items', to='game.world')),
            ],
            options={
                'unique_together': {('world', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('buyback_rate', models.DecimalField(decimal_places=2, default=0.6, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='game.world')),
            ],
            options={
                'unique_together': {('world', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MerchantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('market_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_inventory', to='game.marketitem')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.merchant')),
            ],
            options={
                'unique_together': {('merchant', 'market_item')},
            },
        ),
    ]
