# Generated by Django 5.2.12 on 2026-03-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_tradeorder_merchant_name_tradeorder_side_marketitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysession',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storysession',
            name='last_turn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storysession',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
