# config file version
apiVersion: 1

# list of datasources to insert/update
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <string> url of the prometheus instance
    url: http://prometheus:9090
    # <bool> mark as default datasource. Default: false
    isDefault: true
    # <bool> allow users to edit datasources from the UI. Default: false
    editable: true
    # <int> version of the datasource plugin
    version: 1
    # <bool> allow users to query the datasource directly from the UI. Default: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
